from googleapiclient.discovery import build
from urllib.parse import urlparse, parse_qs
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from tqdm import tqdm
from difflib import SequenceMatcher
import os
from dotenv import load_dotenv
import re

BAD_KEYWORDS = [
    "released on",
    "producer",
    "composer",
    "lyricist",
    "auto-generated",
    "generated by youtube"
]

# =========================
# youtube helpers
# =========================

def get_playlist_id(url):
    query = parse_qs(urlparse(url).query)
    return query.get("list", [None])[0]

def get_playlist_songs(youtube, playlist_id):
    all_items = []
    next_page_token = None

    while True:
        request = youtube.playlistItems().list(
            part="snippet",
            playlistId=playlist_id,
            maxResults=50,
            pageToken=next_page_token
        )

        response = request.execute()
        all_items.extend(response["items"])

        next_page_token = response.get("nextPageToken")
        if not next_page_token:
            break

    return all_items

def get_playlist_title(youtube, playlist_id):
    yt_playlist = youtube.playlists().list(
        part="snippet",
        id=playlist_id
    ).execute()

    return yt_playlist["items"][0]["snippet"]["title"]

def make_key(artist, track):
    return normalize(artist or "") + "::" + clean_track(track)

# =========================
# text utilities
# =========================

def clean(text):
    text = re.sub(r"\(.*?\)", "", text)
    text = re.sub(r"\[.*?\]", "", text)
    return text.strip()

def clean_track(track):
    track = track.lower()
    track = re.sub(r"\(.*?(extended|remix|edit|version).*?\)", "", track)
    track = re.sub(r"\[.*?\]", "", track)
    track = re.sub(r"[^a-z0-9 ]", "", track)
    track = re.sub(r"\s+", " ", track).strip()
    return track

def normalize(text): 
    text = text.lower() 
    text = re.sub(r"[^a-z0-9 ]", "", text) 
    return re.sub(r"\s+", " ", text).strip()

def safe_query(text, max_len=120):
    return text.strip()[:max_len]

def clean_channel(name):
    return name.replace(" - Topic", "").strip()

def is_valid_candidate(text):
    t = text.lower()
    return not any(b in t for b in BAD_KEYWORDS)

# =========================
# parsing
# =========================

def parse_video_title(title):
    title = clean(title)

    for sep in [" - ", " – ", ":"]:
        if sep in title:
            artist, track = title.split(sep, 1)
            return artist.strip(), track.strip()

    return None, title.strip()

def parse_description(desc):
    matches = re.findall(r"(.+?)\s*[·\-–]\s*(.+)", desc)
    return [(right.strip(), left.strip()) for left, right in matches]

# =========================
# scoring
# =========================

def score(track, artist, sp_track):
    sp_name = normalize(sp_track["name"])
    sp_artist = normalize(sp_track["artists"][0]["name"])

    track_score = SequenceMatcher(None, normalize(track), sp_name).ratio()

    artist_score = 0
    if artist:
        artist_score = SequenceMatcher(None, normalize(artist), sp_artist).ratio()

    return (0.6 * track_score) + (1.4 * artist_score)

def artist_match_ok(artist, sp_artist, threshold=0.75):
    if not artist:
        return True
    return SequenceMatcher(
        None,
        normalize(artist),
        normalize(sp_artist)
    ).ratio() >= threshold

# =========================
# chunking
# =========================

def chunk_list(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]


def main(playlist, genre):
    load_dotenv()

    youtube = build("youtube", "v3", developerKey=os.getenv("YOUTUBE_KEY"))

    playlist_url = playlist
    genre = genre.strip().lower()

    playlist_id = get_playlist_id(playlist_url)
    songs = get_playlist_songs(youtube, playlist_id)

    sp = spotipy.Spotify(
        auth_manager=SpotifyOAuth(
            client_id=os.getenv("SPOTIFY_CLIENT_ID"),
            client_secret=os.getenv("SPOTIFY_CLIENT_SECRET"),
            redirect_uri=os.getenv("SPOTIFY_REDIRECT_URI"),
            scope="playlist-modify-private"
        )
    )

    track_uris = []

    #playlist lists for UI later
    youtube_list = []
    track_data = []

    for item in tqdm(songs, desc="Searching Spotify"):
        s = item["snippet"]
        title = s["title"]

        desc = s.get("description", "")
        thumbnails = s.get("thumbnails", {})

        thumbnail = (
            thumbnails.get("high", {}).get("url") or
            thumbnails.get("medium", {}).get("url") or
            thumbnails.get("default", {}).get("url")
        )
        if not thumbnail:
            thumbnail = "https://via.placeholder.com/150"

        video_id = item["snippet"]["resourceId"]["videoId"]

        video_data = youtube.videos().list(
            part="snippet",
            id=video_id
        ).execute()

        video_snippet = video_data["items"][0]["snippet"]
        channel = video_snippet.get("channelTitle", "")

        candidates = []

        # 1. DESCRIPTION (highest priority)
        desc_candidates = []

        for artist, track in parse_description(desc):
            if is_valid_candidate(track) and is_valid_candidate(artist):
                desc_candidates.append((normalize(artist or ""), clean_track(track), thumbnail))

        if desc_candidates:
            candidates = desc_candidates

        else:
            # 2. TITLE fallback ONLY if no description matches
            artist, track = parse_video_title(title)

            if track:
                candidates.append((normalize(artist or ""), clean_track(track), thumbnail))

        for artist, track, tb in candidates:
            if not track:
                continue

            if artist:
                query = f"{artist} {track} {genre}"
                youtube_list.append(["Artist: " + artist, track, tb])
            else:
                query = f"{track} {clean_channel(channel)} {genre}"
                youtube_list.append(["Channel: " + clean_channel(channel), track, tb])

            query = safe_query(query)

            results = sp.search(q=query, type="track", limit=5)
            items = results["tracks"]["items"]

            if not items:
                track_data.append({
                    "uri": None,
                    "artist": artist or "Unavailable",
                    "track": track or "Unavailable",
                    "thumbnail": thumbnail,
                    "status": "not_found"
                })
                continue

            best = None
            best_score = 0

            for it in items:
                sp_artist = it["artists"][0]["name"]
                
                if not artist_match_ok(artist, sp_artist):
                    continue

                s = score(track, artist, it)

                if s > best_score:
                    best_score = s
                    best = it

            if best and best_score > 0.55:
                uri = best["uri"]

                if uri not in track_uris:
                    track_uris.append(uri)
                    
                    track_data.append({
                        "uri": uri,
                        "artist": best["artists"][0]["name"],
                        "track": best["name"],
                        "thumbnail": best["album"]["images"][0]["url"] if best["album"]["images"] else None
                    })

    print("\nTOTAL FOUND:", len(track_uris))

    '''
    playlist = sp.user_playlist_create(
        user=sp.current_user()["id"],
        name=get_playlist_title(youtube, playlist_id),
        public=False
    )

    for chunk in chunk_list(track_uris, 100):
        sp.playlist_add_items(playlist["id"], chunk)
    '''

    return youtube_list, track_data
